### PR TITLE
Fix is_published filtering of GET items/latest request

### LINKED ISSUE #152: scheduled article appears before setted date
# What occurs
On infobox project the item 549d7b049a645d2166f5c9d7, was scheduled to be released at 3pm today, 10/07. But at 10:am it's already published. It seems that push notification was not sent yet.
The time zone setted on site.settings is correct "Sao Paulo".

posts___infobox

### PR DESCRIPTION
**Pull request by t4deu**
Remove invalid and use the correct conditional parameter to return
only the published items in the GET items/latest request.

closes #152

### CODE REVIEW

File: sitebuilder/app/controllers/api/ItemsController.php [hunk 1]
```diff
@@ -179,11 +179,13 @@ public function latest()
 		$parent_id = $this->request->get('params:parent_id');
 
 		$params = [
-			'conditions' => ['site_id' => $this->site()->id],
+			'conditions' => [
+				'site_id' => $this->site()->id,
+				'is_published' => true
```
Comment (juliogreff) [inline sitebuilder/app/controllers/api/ItemsController.php]: Always leave the last comma in a multi-line array

**Comment by juliogreff** [comment]
Good to merge. Squash the commits and put a good message. You're still talking too much about *what* and not enough about *why*.
