### PR TITLE
Fix fatal error on events update

### LINKED ISSUE #118: update_events.php raises a Fatal error: 'String could not be parsed as XML'
I've ran it on CSE env.
No mor informations on logs to know which feed is responsible for it.

```
Fatal error: Uncaught exception 'Exception' with message 'String could not be parsed as XML' in /home/meumobi/PROJECTS/int-meumobilesite.com/releases/20150415113636/sitebuilder/lib/meumobi/sitebuilder/services/UpdateEventsService.php:26
Stack trace:
#0 /home/meumobi/PROJECTS/int-meumobilesite.com/releases/20150415113636/sitebuilder/lib/meumobi/sitebuilder/services/UpdateEventsService.php(26): SimpleXMLElement->__construct('')
#1 /home/meumobi/PROJECTS/int-meumobilesite.com/releases/20150415113636/sitebuilder/script/update_events.php(26): meumobi\sitebuilder\services\UpdateEventsService->call()
#2 /home/meumobi/PROJECTS/int-meumobilesite.com/releases/20150415113636/sitebuilder/config/cli.php(19): {closure}()
#3 /home/meumobi/PROJECTS/int-meumobilesite.com/releases/20150415113636/sitebuilder/script/update_events.php(27): meumobi_lock('update_events_', Object(Closure))
#4 {main}
  thrown in /home/meumobi/PROJECTS/int-meumobilesite.com/releases/20150415113636/sitebuilder/lib/meumobi/sitebuilder/services/UpdateEventsService.php on line 26
```

### PR DESCRIPTION
**Pull request by t4deu**
Fixes fatal errors due to uncaught exceptions and disables the extension if some error occurs during the update, like invalid feeds or categories.

Closes #118

### CODE REVIEW

File: sitebuilder/lib/meumobi/sitebuilder/services/UpdateEventsService.php [hunk 1]
```diff
@@ -6,6 +6,7 @@
 use app\models\items\Events;
 use lithium\data\Connections;
 use Model;
+use Exception;
```
Comment (juliogreff) [inline sitebuilder/lib/meumobi/sitebuilder/services/UpdateEventsService.php]: Order used classes alphabetically

File: sitebuilder/lib/meumobi/sitebuilder/services/UpdateEventsService.php [hunk 2]
```diff
@@ -54,16 +55,19 @@ public function call() {
...
 				$this->logger()->debug('finished feed', ['url' => $feed['url']]);
-			} catch ( Exception $e ) {
-				$this->logger->error('events update error', [
-						'exception' => get_class($e),
-						'message' => $e->getMessage(),
-						'trace' => $e->getTraceAsString()]);
+			} catch (Exception $e) {
+				EventFeed::update(['enabled' => false], ['_id' => $feed['_id']]);
+
+				$this->logger()->error('events update error', [
```
Comment (juliogreff) [inline sitebuilder/lib/meumobi/sitebuilder/services/UpdateEventsService.php]: First parameter is a component, not a message. The "error" should not be there

File: sitebuilder/lib/meumobi/sitebuilder/services/UpdateEventsService.php [hunk 3]
```diff
@@ -53,17 +55,20 @@ public function call() {
...
-			} catch ( Exception $e ) {
-				$this->logger->error('events update error', [
-						'exception' => get_class($e),
-						'message' => $e->getMessage(),
-						'trace' => $e->getTraceAsString()]);
+				Logger::info('events', 'finished feed', ['url' => $feed['url']]);
+			} catch (Exception $e) {
+				EventFeed::update(['enabled' => false], ['_id' => $feed['_id']]);
+
+				Logger::error('events', 'feed update', [
```
Comment (juliogreff) [inline sitebuilder/lib/meumobi/sitebuilder/services/UpdateEventsService.php]: I'm not merging the PR until this is fixed: we should tell that the EventFeed extension was disabled, and also why.

**Comment by juliogreff** [comment]
I noticed that you're re-writing the entire commit before the PR is done. That makes tracking comments very difficult, and we also lose history. Add new commits, squash only when it's ready to merge.

Also, I commented this before: your commits messages are still not following the recommendations: http://who-t.blogspot.nl/2009/12/on-commit-messages.html

File: sitebuilder/lib/meumobi/sitebuilder/services/UpdateEventsService.php [hunk 4]
```diff
@@ -43,27 +48,32 @@ public function call() {
...
+				]);
 			}
-			$stats['end_time'] = microtime(true);
-			$stats['elapsed_time'] = array_unset($stats, 'end_time') -
-			array_unset($stats, 'start_time');
-			$this->logger()->info('finished updating events', $stats);
 		}
+
+		$stats['end_time'] = microtime(true);
+		$stats['elapsed_time'] = array_unset($stats, 'end_time') -
```
Comment (juliogreff) [inline sitebuilder/lib/meumobi/sitebuilder/services/UpdateEventsService.php]: Since you set it only to unset it again, wouldn't it make sense to just set a normal variable instead?

**Comment by juliogreff** [comment]
Disregard last comment, I think the PR is fine to merge. Squash the commits, edit the PR's description and we're good to go.

**Comment by juliogreff** [comment]
When I told you to put the issue number in the description, I really meant the PR, not the commit. The commit should always have the issue number in the first line, preferably at the end. I updated the Best Practices guide to reflect that. Go back and update.

Also, your commit message includes the *what*, but does not yet include the *why*. Read back on the guide I suggested you.

**Comment by juliogreff** [comment]
I was reviewing the other open tickets, and it seems like #82 should be fixed before this one can be merged. We don't have to make any changes to this PR (except fixing the commit message as I said above), but I won't merge until #82 gets fixed.
