### PR TITLE
FIX: Added filter for only visible categories in /items/search requests

### LINKED ISSUE #424: /items/search returns items from hidden categories
I've setted a category of contacts as hidden (uncheck visibility).
Then items within this category are retrieved by /items/search?type=contacts request

### PR DESCRIPTION
**Pull request by danielindiano**
FIX: Closes #424, /items/search returns items from hidden categories

It filter the query to show only items from visible categories, even if the parent_id parameter is present.

### CODE REVIEW

File: sitebuilder/app/controllers/api/ItemsController.php [hunk 1]
```diff
@@ -143,12 +143,21 @@ public function search()
...
+
 		$conditions = $this->postConditions($this->request->query, [
 			'title' => 'like',
 			'description' => 'like'
 		]);
 		$conditions['is_published'] = true;
-		$conditions['site_id'] = $this->site()->id;
+		$conditions['site_id'] = $this->site()->id;		
+		$conditions['parent_id'] = [ '$in' => $visible_categories_ids ];		
+		if ( $this->request->get('query:parent_id') ) {
```
Comment (juliogreff) [inline sitebuilder/app/controllers/api/ItemsController.php]: Be careful with the coding standards. There's no space inside parents of ifs. We use the Zend Style Guide.

Other than that, PR looks good. Fix it and I'll merge right away.
