### PR TITLE
Only send push notification when a item is created and is not from a feed first import

### LINKED ISSUE #103: First import of Push Category should not raise Pushes
# What occurs
If we create a new category with push options enabled and RSS extension. On import all items created will raise a push, ie. if feed provide 20 items it should raise 20 Push!
Same issue occurs if we remove all items to re-import them.

# How to reproduce
Create a new category with push options enabled and RSS extension. Check logs to catch Push request
```
$ tail log/sitebuilder.log | grep "push_notification"
```
# Why it happens
The rule is that any item created raise a push.
But when the category is new or has been erased, that means with priority == 1 then it should not.

# How to fix
Only create push job if category of item has priority value equals to 0.

### PR DESCRIPTION
**Pull request by t4deu**
Closes #103, #101 and #97

### CODE REVIEW

File: sitebuilder/app/controllers/items_controller.php [hunk 1]
```diff
@@ -44,11 +45,9 @@ public function add($parent_id = null)
...
 			$item->site_id = $site->id;
 			$item->type = $parent->type;
-			$validator = new ItemsPersistenceValidator();
-			$validationResult = $validator->validate($item);
-
-			if ($validationResult->isValid() && $item->save()) {
-				$item->addMediaFileSize();//TODO check if is the best way to do this, at first I tried tu use a before save filter, but din't work
+			$itemCreationService = new ItemCreation();
+			if ($itemCreationService->create($item)) {
+				$item->addMediaFileSize();//TODO add to creation service
```
Comment (juliogreff) [inline sitebuilder/app/controllers/items_controller.php]: Not only the media file size, but also include everything related to item creation in the service. That means also the images.

Comment (t4deu) [inline sitebuilder/app/controllers/items_controller.php]: I think that some refactoring must be done to include the images in the service.
Because they are treated differently.
In the feed import they are downloaded while in the dashboard they are only updated because they already had been downloaded previously.

Comment (juliogreff) [inline sitebuilder/app/controllers/items_controller.php]: Ok, let's leave it out for the moment then

File: sitebuilder/features/articles.feature [hunk 2]
```diff
@@ -0,0 +1,19 @@
+Feature: Articles
```
Comment (juliogreff) [inline sitebuilder/features/articles.feature]: If I run this, do all tests pass? I'm OK with adding automated testing, but we should be responsible for keeping them up to date *at all times*

File: sitebuilder/app/models/Items.php [hunk 3]
```diff
@@ -675,10 +660,6 @@ public static function exportTo($format = 'csv', $conditions = array()) {
 	return Items::addThumbnails($self, $params, $chain);
 });
 
-Items::applyFilter('save', function($self, $params, $chain) {
```
Comment (juliogreff) [inline sitebuilder/app/models/Items.php]: Do we have any other observer (or behavior inside more general observers) that apply only to item creation? If we do, we also should move them all to the service.

File: sitebuilder/lib/meumobi/sitebuilder/workers/UpdateFeedsWorker.php [hunk 4]
```diff
@@ -41,7 +43,7 @@ public function perform()
 	{
 		$start = microtime(true);
 		$this->logger()->info('updating feeds', [ 'priority' => $this->priority ]);
-
+		$this->itemCreationService = new ItemCreation();
```
Comment (juliogreff) [inline sitebuilder/lib/meumobi/sitebuilder/workers/UpdateFeedsWorker.php]: Don't ever assign services to instance variables. There's absolutely no need for it, it's only a source of bugs.

File: sitebuilder/lib/meumobi/sitebuilder/services/ItemCreation.php [hunk 5]
```diff
@@ -0,0 +1,58 @@
...
+use meumobi\sitebuilder\WorkerManager;
+
+class ItemCreation
+{
+	protected $item;
+	protected $logger;
+
+	public function __construct()
+	{
+		$this->logger = Logger::logger();
```
Comment (juliogreff) [inline sitebuilder/lib/meumobi/sitebuilder/services/ItemCreation.php]: Prefer using the static method from the logger class instead of using the instances. They'll force you to specify a component, and that's very useful for grepping logs

File: sitebuilder/lib/meumobi/sitebuilder/services/ItemCreation.php [hunk 6]
```diff
@@ -0,0 +1,58 @@
...
+	}
+
+	public function create($item, $sendPush = true)
+	{
+		$this->item = $item;
```
Comment (juliogreff) [inline sitebuilder/lib/meumobi/sitebuilder/services/ItemCreation.php]: Avoid using instance variables inside services when there's no need for it. You could've very well just have passed the item as a parameter to the sendPushNotification method.

File: sitebuilder/lib/meumobi/sitebuilder/services/ItemCreation.php [hunk 7]
```diff
@@ -0,0 +1,58 @@
...
+{
+	protected $item;
+	protected $logger;
+
+	public function __construct()
+	{
+		$this->logger = Logger::logger();
+	}
+
+	public function create($item, $sendPush = true)
```
Comment (juliogreff) [inline sitebuilder/lib/meumobi/sitebuilder/services/ItemCreation.php]: Avoid using "magic" boolean parameters. Having create($item, ['sendPush' => true]) is much clearer than create($item, true)

File: sitebuilder/lib/meumobi/sitebuilder/services/ItemCreation.php [hunk 8]
```diff
@@ -0,0 +1,58 @@
...
+		$validationResult = $validator->validate($item);
+		if ($validationResult->isValid()) {
+			$item->save();
+			$this->logger->debug('item created', [
+				'item id' => $item->id(),
+				'category id' => $item->site_id,
+				'site id' => $item->parent_id
+			]);
+			if ($sendPush)
+				$this->sendPushNotification();
```
Comment (juliogreff) [inline sitebuilder/lib/meumobi/sitebuilder/services/ItemCreation.php]: We've discussed this plenty of times before: if you use more than one line, *always* use braces.

File: sitebuilder/lib/meumobi/sitebuilder/services/ItemCreation.php [hunk 9]
```diff
@@ -0,0 +1,58 @@
...
+			return true;
+		} else {
+			$this->logger->error('item can\'t be created', [
```
Comment (juliogreff) [inline sitebuilder/lib/meumobi/sitebuilder/services/ItemCreation.php]: Use double quotes whenever you'd need to escape single quotes in the string

Comment (juliogreff) [inline sitebuilder/lib/meumobi/sitebuilder/services/ItemCreation.php]: Also, how do you tell the interface (either the web interface or the API) that the item creation failed? How do you inform all the validation errors? This logic should also be updated.

**Comment by juliogreff** [comment]
Are you sure you covered all the places where we need to create items? I'm pretty sure that the API can also do it, and I haven't seen any code related to that.

File: sitebuilder/app/controllers/items_controller.php (hunk 1 above)
Comment (juliogreff) [inline sitebuilder/app/controllers/items_controller.php]: Either way, I'm not merging this while we have TODOs around

File: sitebuilder/lib/meumobi/sitebuilder/services/ItemCreation.php [hunk 10]
```diff
@@ -0,0 +1,58 @@
...
+	}
+
+	public function create($item, $sendPush = true)
+	{
+		$this->item = $item;
+		$validator = new ItemsPersistenceValidator();
+		$validationResult = $validator->validate($item);
+		if ($validationResult->isValid()) {
+			$item->save();
+			$this->logger->debug('item created', [
```
Comment (juliogreff) [inline sitebuilder/lib/meumobi/sitebuilder/services/ItemCreation.php]: All the logs I've seen in this PR should be *info* instead of *debug*. And we don't have any debug information that would be useful. For example, if I don't see a "push notification job created" message in the output, I'd like to know why. The way it is now, I don't know if something else happened or if it's intentional.

File: sitebuilder/lib/meumobi/sitebuilder/services/ItemCreation.php [hunk 11]
```diff
@@ -0,0 +1,58 @@
...
+
+	protected function sendPushNotification()
+	{
+		$category = $this->item->parent();
+		if ($this->item->is_published && $category->notification) {
+			$job = WorkerManager::enqueue('push_notification', [
+				'item_id' => $this->item->id(),
+				'category_id' => $this->item->parent_id
+			]);
+			$this->logger->debug('push notification job created', [
```
Comment (juliogreff) [inline sitebuilder/lib/meumobi/sitebuilder/services/ItemCreation.php]: This should live in the WorkerManager::enqueue method. Otherwise, we'll need to log this *every single time* we enqueue a job somewhere.

File: sitebuilder/lib/meumobi/sitebuilder/validators/ItemsPersistenceValidator.php [hunk 12]
```diff
@@ -48,7 +48,7 @@ protected function validateRule($rule, $value)
 
 	protected function notEmptyMedias($medias)
 	{
-		$check = ['title', 'url', 'type'];
```
Comment (juliogreff) [inline sitebuilder/lib/meumobi/sitebuilder/validators/ItemsPersistenceValidator.php]: Why did you remove the title? Does it have anything to do with the feature you're developing?

File: sitebuilder/app/models/Items.php (hunk 3 above)
Comment (t4deu) [inline sitebuilder/app/models/Items.php]: Yes, the Items::addOrder observer, the others observers are applied when saving and updates an item

File: sitebuilder/lib/meumobi/sitebuilder/workers/UpdateFeedsWorker.php (hunk 4 above)
Comment (t4deu) [inline sitebuilder/lib/meumobi/sitebuilder/workers/UpdateFeedsWorker.php]: OK, I'll fix

File: sitebuilder/lib/meumobi/sitebuilder/services/ItemCreation.php (hunk 7 above)
Comment (t4deu) [inline sitebuilder/lib/meumobi/sitebuilder/services/ItemCreation.php]: This way really is better, thanks

File: sitebuilder/lib/meumobi/sitebuilder/services/ItemCreation.php (hunk 9 above)
Comment (t4deu) [inline sitebuilder/lib/meumobi/sitebuilder/services/ItemCreation.php]: The method returns TRUE if the item item is successfully created.
And currently there is no way to DISPLAY the validation errors through the web interface, only a flash message to inform the user.

But I agree that we should be able to get the validation errors from the service. 

To do this we could return the ValidationResult instead of a boolean, but it not seems that is the better solution.

File: sitebuilder/lib/meumobi/sitebuilder/services/ItemCreation.php (hunk 11 above)
Comment (t4deu) [inline sitebuilder/lib/meumobi/sitebuilder/services/ItemCreation.php]: You mean the log message right? I will move the log to the WorkerManager::enqueue

File: sitebuilder/lib/meumobi/sitebuilder/services/ItemCreation.php (hunk 9 above)
Comment (juliogreff) [inline sitebuilder/lib/meumobi/sitebuilder/services/ItemCreation.php]: I see no problem with returning the ValidationResult. Why do you think it's not so good?

File: sitebuilder/lib/meumobi/sitebuilder/validators/ItemsPersistenceValidator.php (hunk 12 above)
Comment (t4deu) [inline sitebuilder/lib/meumobi/sitebuilder/validators/ItemsPersistenceValidator.php]: Because some rss feed don't have the media titles, and because of this they aren't created

File: sitebuilder/lib/meumobi/sitebuilder/services/ItemCreation.php (hunk 9 above)
Comment (t4deu) [inline sitebuilder/lib/meumobi/sitebuilder/services/ItemCreation.php]: Because to check if the item has created gonna need to check if is "isValid", don't sound right:
> $itemCreationService->create($item)->isValid()

Comment (juliogreff) [inline sitebuilder/lib/meumobi/sitebuilder/services/ItemCreation.php]: You can return multiple values:

```
list($created, $errors) = $service->create($item);
```

You'll probably need to return the item as well, so you can do something like this instead:

```
// $item is null, $errors is an array when it fails
// or $item is an item, and $errors is an empty array when it succeeds
list($item, $errors) = $service->create($item);
```

File: sitebuilder/lib/meumobi/sitebuilder/services/ItemCreation.php [hunk 13]
```diff
@@ -0,0 +1,64 @@
...
+
+use meumobi\sitebuilder\validators\ItemsPersistenceValidator;
+use meumobi\sitebuilder\Logger;
+use meumobi\sitebuilder\WorkerManager;
+
+class ItemCreation
+{
+	public function create($item, $sendPush = true)
+	{
+		$this->addOrder($item);
```
Comment (juliogreff) [inline sitebuilder/lib/meumobi/sitebuilder/services/ItemCreation.php]: Why do you add the order even before you know if the item is valid?

File: sitebuilder/lib/meumobi/sitebuilder/services/ItemCreation.php (hunk 10 above)
Comment (juliogreff) [inline sitebuilder/lib/meumobi/sitebuilder/services/ItemCreation.php]: Are you even running the code before pushing? There's no $this->logger anymore.

Comment (t4deu) [inline sitebuilder/lib/meumobi/sitebuilder/services/ItemCreation.php]: No, the code has not executed, because it has not finished yet, but since you advice me to commit chances even if they are unfinished I see no problem

Comment (juliogreff) [inline sitebuilder/lib/meumobi/sitebuilder/services/ItemCreation.php]: Unfinished is fine, but it has to be in a working state. And by working I mean at least running without errors, even if the functionality is not there yet.

File: sitebuilder/lib/meumobi/sitebuilder/services/ItemCreation.php (hunk 13 above)
Comment (t4deu) [inline sitebuilder/lib/meumobi/sitebuilder/services/ItemCreation.php]: Yes, my bad, will put after validation

File: sitebuilder/lib/meumobi/sitebuilder/services/ItemCreation.php (hunk 10 above)
Comment (t4deu) [inline sitebuilder/lib/meumobi/sitebuilder/services/ItemCreation.php]: Ok, I will remember next time, thanks

File: sitebuilder/lib/meumobi/sitebuilder/services/ItemCreation.php (hunk 7 above)
Comment (t4deu) [inline sitebuilder/lib/meumobi/sitebuilder/services/ItemCreation.php]: Constants will be used Instead of strings keys for the "create" method options, to avoid misspelling and run time errors:
> create($item, [ItemCreation::SEND_PUSH, ItemCreation::ADD_MEDIA_FILESIZE]);

File: sitebuilder/lib/meumobi/sitebuilder/services/ItemCreation.php (hunk 9 above)
Comment (t4deu) [inline sitebuilder/lib/meumobi/sitebuilder/services/ItemCreation.php]: I prefer the first way, since the $item is passed by reference to the "create" method, there is no need to return it:

> list($created, $errors) = $service->create($item);

File: sitebuilder/lib/meumobi/sitebuilder/workers/UpdateFeedsWorker.php (hunk 4 above)
Comment (t4deu) [inline sitebuilder/lib/meumobi/sitebuilder/workers/UpdateFeedsWorker.php]: But how to use the service in the UpdateFeedsWorker::updateArticle without creating an new instance on every method call?

I can pass as param in the array_walk?
```php
$service = new ItemCreation();                             
array_walk($this->getExtensionsIds(), [$this, 'updateFromFeed'], $service); 
```

File: sitebuilder/lib/meumobi/sitebuilder/WorkerManager.php [hunk 14]
```diff
@@ -15,7 +15,14 @@ public static function enqueue($type, $params, $priority = Worker::PRIORITY_LOW)
 			'priority' => $priority,
 			'params' => $params
 		]);
-		return $job->save();
+		$job->save();
+		Logger::logger()->info('job created', [
```
Comment (juliogreff) [inline sitebuilder/lib/meumobi/sitebuilder/WorkerManager.php]: You're still not using the static methods, this is just using the instance directly.

Comment (t4deu) [inline sitebuilder/lib/meumobi/sitebuilder/WorkerManager.php]: Sorry, I have never seen these static methods of the Logger class being used in other files, the only place it's used is in the ApiController. What are the correct values for the "component" param? can you give some examples?

Comment (juliogreff) [inline sitebuilder/lib/meumobi/sitebuilder/WorkerManager.php]: You can give it any name, choose anything that you could grep for. I'd call it "items" for starters, we can always go back and change it later if it ends up being too general

File: sitebuilder/app/controllers/api/ItemsController.php [hunk 15]
```diff
@@ -281,8 +287,13 @@ public function create()
 		$item->set($this->request->data);
 		$item->site_id = $this->site()->id;
 		$item->type = $category->type;
+		$itemCreationService = new ItemCreation();
 
-		if ($item->save()) {
+		list ($created, $errors) = $itemCreationService->create($item, [
```
Comment (juliogreff) [inline sitebuilder/app/controllers/api/ItemsController.php]: You'd probably want to return the errors in the API. If I'm trying to create an item, and only get a generic error message back, I won't be very likely to find out what's wrong.

File: sitebuilder/lib/meumobi/sitebuilder/services/ItemCreation.php [hunk 16]
```diff
@@ -0,0 +1,74 @@
...
+				'site id' => $item->parent_id,
+				'options' => $options,
+				'errors' => $validationResult->errors(),
+			]);
+			$created = false;
+		}
+		return [$created, $validationResult->errors()];
+	}
+
+	public function addMediaFileSize($item)
```
Comment (juliogreff) [inline sitebuilder/lib/meumobi/sitebuilder/services/ItemCreation.php]: This should be a protected method, since you have a parameter "addMediaFileSize" that makes it get called. On the update action, you probably want to just keep calling $item->addMediaFileSize for the moment.

File: sitebuilder/lib/meumobi/sitebuilder/workers/UpdateFeedsWorker.php [hunk 17]
```diff
@@ -175,6 +177,7 @@ protected function getItem($feedItem)
 	protected function updateArticle($item, $feedItem)
 	{
 		$images = $this->getArticleImages($feedItem);
+		$options = [];
```
Comment (juliogreff) [inline sitebuilder/lib/meumobi/sitebuilder/workers/UpdateFeedsWorker.php]: This is not being used any more. Please delete.

File: sitebuilder/lib/meumobi/sitebuilder/workers/UpdateFeedsWorker.php (hunk 4 above)
Comment (juliogreff) [inline sitebuilder/lib/meumobi/sitebuilder/workers/UpdateFeedsWorker.php]: Passing it as a parameter is fine. I'd pass it as an associative array though.

File: sitebuilder/lib/meumobi/sitebuilder/services/ItemCreation.php [hunk 18]
```diff
@@ -0,0 +1,74 @@
...
+			$this->addOrder($item);
+			$item->save();
+			Logger::logger()->info('item created', [
+				'item id' => $item->id(),
+				'category id' => $item->site_id,
+				'site id' => $item->parent_id,
+				'options' => $options,
+			]);
+
+			if (isset($options['sendPush']) && $options['sendPush']) {
```
Comment (juliogreff) [inline sitebuilder/lib/meumobi/sitebuilder/services/ItemCreation.php]: You probably want to extract the "isset($thing[$i]) && $thing[$i]" into it's own function. Also, you'd want to validate that in the way in, so you're sure you're not passing parameters you don't know how to deal with.

File: sitebuilder/lib/meumobi/sitebuilder/services/ItemCreation.php [hunk 19]
```diff
@@ -0,0 +1,74 @@
...
+			}
+			if (isset($options['addMediaFileSize']) && $options['addMediaFileSize']) {
+				$this->addMediaFileSize($item);
+			}
+			$created = true;
+		} else {
+			Logger::logger()->error("item can't be created", [
+				'category id' => $item->site_id,
+				'site id' => $item->parent_id,
+				'options' => $options,
```
Comment (juliogreff) [inline sitebuilder/lib/meumobi/sitebuilder/services/ItemCreation.php]: Getting the options in the log here is irrelevant. Also, it's not an error (because you dealt with it), it's just an info.

File: sitebuilder/lib/meumobi/sitebuilder/services/ItemCreation.php [hunk 20]
```diff
@@ -0,0 +1,74 @@
...
+		$validator = new ItemsPersistenceValidator();
+		$validationResult = $validator->validate($item);
+		if ($validationResult->isValid()) {
+			$this->addOrder($item);
+			$item->save();
+			Logger::logger()->info('item created', [
+				'item id' => $item->id(),
+				'category id' => $item->site_id,
+				'site id' => $item->parent_id,
+				'options' => $options,
```
Comment (juliogreff) [inline sitebuilder/lib/meumobi/sitebuilder/services/ItemCreation.php]: The options are irrelevant here too. If you want to log them, do that when you call the service, not in every inner log.

File: sitebuilder/lib/meumobi/sitebuilder/services/ItemCreation.php [hunk 21]
```diff
@@ -0,0 +1,74 @@
...
+		$hasMedias = count($item->medias->to('array'));
+		if ($item->id() && $hasMedias) {
+			WorkerManager::enqueue('media_filesize', ['item_id' => $item->id()]);
+		}
+	}
+
+	protected function sendPushNotification($item)
+	{
+		$category = $item->parent();
+		if ($item->is_published && $category->notification) {
```
Comment (juliogreff) [inline sitebuilder/lib/meumobi/sitebuilder/services/ItemCreation.php]: If we don't enqueue the job, we still have no idea why without having to poke at the code. Add debug log information here explaining why the job was skipped.

File: sitebuilder/lib/meumobi/sitebuilder/workers/UpdateFeedsWorker.php [hunk 22]
```diff
@@ -202,7 +205,11 @@ protected function updateArticle($item, $feedItem)
 		);
 
 		$item->set($data);
-		$item->save();
+
+		list($created, $errors) = $this->itemCreationService->create($item, [
```
Comment (juliogreff) [inline sitebuilder/lib/meumobi/sitebuilder/workers/UpdateFeedsWorker.php]: You're using inconsistent formatting for list(). Choose one and stick with it. I prefer not having the space between the call and the parens.

File: sitebuilder/features/articles.feature (hunk 2 above)
Comment (juliogreff) [inline sitebuilder/features/articles.feature]: This one remains unanswered.

File: sitebuilder/lib/meumobi/sitebuilder/services/ItemCreation.php [hunk 23]
```diff
@@ -0,0 +1,74 @@
...
+			]);
+			$created = false;
+		}
+		return [$created, $validationResult->errors()];
+	}
+
+	public function addMediaFileSize($item)
+	{
+		$hasMedias = count($item->medias->to('array'));
+		if ($item->id() && $hasMedias) {
```
Comment (juliogreff) [inline sitebuilder/lib/meumobi/sitebuilder/services/ItemCreation.php]: It seems to me like you'd always have the id, so I don't see the point of this check. Also, debug logs for when the job is not created.

File: sitebuilder/lib/meumobi/sitebuilder/services/ItemCreation.php (hunk 18 above)
Comment (t4deu) [inline sitebuilder/lib/meumobi/sitebuilder/services/ItemCreation.php]: I will add an "applyOption" method, and use array_walk to call it:
```php
  protected function applyOption($value, $option, $item)                         
  {                                                                              
    if (!method_exists($this, $option)) {                                        
      throw new \Exception('invalid creation option');                           
    }                                                                            
    $this->$option($item);                                                       
  }
```

Comment (juliogreff) [inline sitebuilder/lib/meumobi/sitebuilder/services/ItemCreation.php]: That is over-engineered and not very general.

```
$options = $this->validateOptions($options, ['addMediaFileSize', '...'];
$addMediaFileSize = $options['addMediaFileSize'];
```

This should return an array with all the required keys (set to null if they're not present);

Comment (juliogreff) [inline sitebuilder/lib/meumobi/sitebuilder/services/ItemCreation.php]: Or even:

```
list($addMediaFileSize, $sendPush) = $this->validateOptions($options, ['addMediaFileSize', 'sendPush']);
```

**Comment by juliogreff** [comment]
I still have two main concerns with this pull request:

* In the web interface, we're just swallowing the errors and not showing the user how to fix them. We should take care of that.
* There's still *a lot* of duplicated code in the controllers that we need to move to the services. For example:

```
		$site = $this->getCurrentSite();
		$parent = Model::load('Categories')->firstById($parent_id);
		$classname = '\app\models\items\\' . Inflector::camelize($parent->type);
		$item = $classname::create();
		$item->type = $parent->type;
```

**Comment by t4deu** [comment]
But the $item instance is necessary before create the item, to dynamically generate the form by the item type

**Comment by juliogreff** [comment]
I don't understand your last comment:

> But the $item instance is necessary before create the item, to dynamically generate the form by the item type

**Comment by t4deu** [comment]
The create/update html forms in the web interface need an instance of the Item to be generated

**Comment by juliogreff** [comment]
You have the instance, I just don't see the problem.

**Comment by t4deu** [comment]
It's about your last comment:
>There's still a lot of duplicated code in the controllers that we need to move to the services. For example:
        $site = $this->getCurrentSite();
        $parent = Model::load('Categories')->firstById($parent_id);
        $classname = '\app\models\items\\' . Inflector::camelize($parent->type);
        $item = $classname::create();
        $item->type = $parent->type;

**Comment by juliogreff** [comment]
I don't talk about removing the instance. I talk about removing the code duplication, and moving this behavior inside the service.

**Comment by t4deu** [comment]
Got it! I'll think of a way to accomplish this

File: sitebuilder/lib/meumobi/sitebuilder/services/ItemCreation.php [hunk 24]
```diff
@@ -0,0 +1,118 @@
...
+use meumobi\sitebuilder\validators\ItemsPersistenceValidator;
+use meumobi\sitebuilder\Logger;
+use meumobi\sitebuilder\WorkerManager;
+
+class ItemCreation
+{
+	public function build($data)
+	{
+		$category = Model::load('Categories')->firstById($data['parent_id']);
+		$classname = '\app\models\items\\' . \Inflector::camelize($category->type);
```
Comment (juliogreff) [inline sitebuilder/lib/meumobi/sitebuilder/services/ItemCreation.php]: Still some backslashes lying around

File: sitebuilder/lib/meumobi/sitebuilder/services/ItemCreation.php [hunk 25]
```diff
@@ -0,0 +1,118 @@
...
+		$validationResult = $validator->validate($item);
+
+		if ($validationResult->isValid()) {
+			$this->addOrder($item);
+			$item->save();
+
+			Logger::info('items', 'item created', [
+				'item id' => $item->id(),
+				'category id' => $item->site_id,
+				'site id' => $item->parent_id,
```
Comment (juliogreff) [inline sitebuilder/lib/meumobi/sitebuilder/services/ItemCreation.php]: site_id and parent_it seem to be switched here

File: sitebuilder/lib/meumobi/sitebuilder/services/ItemCreation.php [hunk 26]
```diff
@@ -0,0 +1,118 @@
...
+				'options' => $options,
```
Comment (juliogreff) [inline sitebuilder/lib/meumobi/sitebuilder/services/ItemCreation.php]: I believe I commented this before, but having the options here seems a bit pointless. If you want to log them, do it when you call the service.

File: sitebuilder/lib/meumobi/sitebuilder/services/ItemCreation.php [hunk 27]
```diff
@@ -0,0 +1,118 @@
...
+
+			if ($sendPush) {
+				$this->sendPushNotification($item);
+			}
+
+			$created = true;
+		} else {
+			Logger::info('items', "item can't be created", [
+				'category id' => $item->site_id,
+				'site id' => $item->parent_id,
```
Comment (juliogreff) [inline sitebuilder/lib/meumobi/sitebuilder/services/ItemCreation.php]: They're switched here too

File: sitebuilder/lib/meumobi/sitebuilder/services/ItemCreation.php [hunk 28]
```diff
@@ -0,0 +1,118 @@
...
+
+		return [$created, $validationResult->errors()];
+	}
+
+	protected function validateOptions($options, $validOptions)
+	{
+		$invalidOptions = array_diff(array_keys($options), $validOptions);
+
+		if ($invalidOptions) {
+			throw new \Exception('invalid options: ' . implode(', ', $invalidOptions));
```
Comment (juliogreff) [inline sitebuilder/lib/meumobi/sitebuilder/services/ItemCreation.php]: Backslash

File: sitebuilder/lib/meumobi/sitebuilder/services/ItemCreation.php [hunk 29]
```diff
@@ -0,0 +1,118 @@
...
+	{
+		$category = $item->parent();
+
+		if ($item->is_published && $category->notification) {
+			$job = WorkerManager::enqueue('push_notification', [
+				'item_id' => $item->id(),
+				'category_id' => $item->parent_id
+			]);
+		} else {
+			Logger::debug('items', "not creating push_notification job", [
```
Comment (juliogreff) [inline sitebuilder/lib/meumobi/sitebuilder/services/ItemCreation.php]: Use single quotes unless you're interpolating variables.

File: sitebuilder/lib/meumobi/sitebuilder/services/ItemCreation.php [hunk 30]
```diff
@@ -0,0 +1,118 @@
...
+				'reason' => [
+					'published' => $item->is_published,
+					'push enabled in category' => $category->notification
+				]
+			]);
+		}
+	}
+
+	/**
+	 * set the order value with the last order plus 1
```
Comment (juliogreff) [inline sitebuilder/lib/meumobi/sitebuilder/services/ItemCreation.php]: This comment seems a bit pointless. It seems to me that's very obvious what the code here does.

File: sitebuilder/lib/meumobi/sitebuilder/validators/ItemsPersistenceValidator.php [hunk 31]
```diff
@@ -10,27 +10,31 @@ class ItemsPersistenceValidator implements Validator
...
+		'type' => [
+			'validType' => 'invalid_type_error'
 		],
 		'title' => [
-			'notEmpty' => 'required_value_error_message'
+			'notEmpty' => 'required_value_error'
 		],
 		'medias' => [
-			'notEmptyMedias' => 'required_media_error_message'
+			'notEmptyMedias' => 'required_media_error'
```
Comment (juliogreff) [inline sitebuilder/lib/meumobi/sitebuilder/validators/ItemsPersistenceValidator.php]: Why are we changing all those values here?

File: sitebuilder/lib/meumobi/sitebuilder/validators/ItemsPersistenceValidator.php [hunk 32]
```diff
@@ -38,17 +42,29 @@ public function validate($entity)
...
 	}
 
-	protected function notEmptyMedias($medias)
+	protected function validSite($siteId, $item)
+	{
+		$category = $item->parent();
+		return $category->site_id == $siteId;
+	}
+
+	protected function validType($type, $item)
```
Comment (juliogreff) [inline sitebuilder/lib/meumobi/sitebuilder/validators/ItemsPersistenceValidator.php]: Since we build the class from the category's type anyway, does this validation still make sense?

File: sitebuilder/lib/meumobi/sitebuilder/workers/UpdateFeedsWorker.php [hunk 33]
```diff
@@ -29,6 +31,7 @@ class UpdateFeedsWorker extends Worker
 	protected $category;
 	protected $extension;
 	protected $priority = Worker::PRIORITY_LOW;
+	protected $itemCreationService;
```
Comment (juliogreff) [inline sitebuilder/lib/meumobi/sitebuilder/workers/UpdateFeedsWorker.php]: I think this was already commented before: don't put services in instance variables as much as possible. They're supposed to be stateless. Create them as late as possible, and avoid sharing.

File: sitebuilder/lib/meumobi/sitebuilder/validators/ItemsPersistenceValidator.php (hunk 32 above)
Comment (t4deu) [inline sitebuilder/lib/meumobi/sitebuilder/validators/ItemsPersistenceValidator.php]: Yes, because the value can be changed before save.

File: sitebuilder/lib/meumobi/sitebuilder/validators/ItemsPersistenceValidator.php (hunk 31 above)
Comment (t4deu) [inline sitebuilder/lib/meumobi/sitebuilder/validators/ItemsPersistenceValidator.php]: I thought it makes more sense remove the "_message" part.

File: sitebuilder/lib/meumobi/sitebuilder/services/ItemCreation.php (hunk 25 above)
Comment (t4deu) [inline sitebuilder/lib/meumobi/sitebuilder/services/ItemCreation.php]: Wow, sorry

File: sitebuilder/lib/meumobi/sitebuilder/workers/UpdateFeedsWorker.php (hunk 33 above)
Comment (t4deu) [inline sitebuilder/lib/meumobi/sitebuilder/workers/UpdateFeedsWorker.php]: About the sharing, I commented previously that I will pass the service as parameter to the array_walk, you said it's fine, this still OK or I need to create a new instance of the service every time I need save the item?

Comment (juliogreff) [inline sitebuilder/lib/meumobi/sitebuilder/workers/UpdateFeedsWorker.php]: Sorry, I keep forgetting this is a loop.

I'd usually advise against it, but since it's kind of performance critical, passing it as a parameter is fine in this case. Still, don't put in instance vars.

File: sitebuilder/lib/meumobi/sitebuilder/services/ItemCreation.php [hunk 34]
```diff
@@ -0,0 +1,115 @@
...
+			$this->addOrder($item);
+			$item->save();
+
+			Logger::info('items', 'item created', [
+				'item id' => $item->id(),
+				'site id' => $item->site_id,
+				'category id' => $item->parent_id,
+			]);
+
+			list($addMediaFileSize, $sendPush) = $this->validateOptions($options, ['addMediaFileSize', 'sendPush']);
```
Comment (juliogreff) [inline sitebuilder/lib/meumobi/sitebuilder/services/ItemCreation.php]: I think I'd move this to the top of the method. This way, it always validates the parameters, even if the item is not valid, for example.

Comment (t4deu) [inline sitebuilder/lib/meumobi/sitebuilder/services/ItemCreation.php]: Don't understand, move what? The validation already is the first thing done at the create method

**Comment by juliogreff** [comment]
Error management for this PR is still not ok.

Two examples:

* When I try to create an item via the web interface and it's invalid, I just get a "Sorry, we can't save the item" with no reason why. That is not acceptable from a user's point of view. We should always point at least one error message so the user can fix the issue and proceed.
* From the API, I get the response below. There are two issues here. First one, I believe the other endpoints return an array of strings, not an object. We should be consistent there. Second, "required_value_error" is a system concept, and the API user certainly doesn't care about that. We should return a meaningful message instead.

```
{"error":"could not save item","errors":{"title":"required_value_error"}}
```

**Comment by t4deu** [comment]
In the web interface: add the first error to the flash message, like this:  "Sorry, can't save item. Title is empty"

**Comment by t4deu** [comment]
the [POST /{domain}/items/{id}/add](https://github.com/meumobi/sitebuilder/blob/master/doc/api_specs.md#post-domainitemsidadd) gives 404, apparently isn't is configured in the routes of the file config/initializer/dispatcher.php anymore.

I remove the action from the controller or add to the routes?

I did not find the commit when change was made

**Comment by juliogreff** [comment]
Feel free to remove the action from the controller.

File: sitebuilder/app/controllers/api/ItemsController.php [hunk 35]
```diff
@@ -297,7 +248,16 @@ public function create()
 			$this->response->status(201);
 			return $item->toJSON($this->visitor());
 		} else {
+			$errors = array_reduce($errors, function($messages, $error){
```
Comment (juliogreff) [inline sitebuilder/app/controllers/api/ItemsController.php]: What you really want here is a map instead of a reduce.

File: sitebuilder/app/controllers/items_controller.php [hunk 36]
```diff
@@ -78,17 +77,17 @@ public function add($parent_id = null)
 				if ($this->isXhr()) {
 					$this->respondToJSON(array(
 						'refresh' => '/items/add/' . $parent_id,
-						'error' => s('Sorry, we can\'t save the item')
+						'error' => s("Sorry, we can't save the item. %s", s(reset($errors))),
```
Comment (juliogreff) [inline sitebuilder/app/controllers/items_controller.php]: Why are you using a reset here? Wouldn't a [0] suffice?

Comment (t4deu) [inline sitebuilder/app/controllers/items_controller.php]: No, because it's a multidimensional array

Comment (juliogreff) [inline sitebuilder/app/controllers/items_controller.php]: ```array_values[0]``` then? It's much more explicit about what it does

File: sitebuilder/app/controllers/api/ItemsController.php (hunk 35 above)
Comment (t4deu) [inline sitebuilder/app/controllers/api/ItemsController.php]: But the errors are a multi dimensional array, that is turned into a json object in the response

File: sitebuilder/app/controllers/items_controller.php (hunk 36 above)
Comment (t4deu) [inline sitebuilder/app/controllers/items_controller.php]: ok

File: sitebuilder/app/controllers/api/ItemsController.php (hunk 35 above)
Comment (juliogreff) [inline sitebuilder/app/controllers/api/ItemsController.php]: I'd suggest ```array_values``` again then

File: sitebuilder/app/controllers/api/ItemsController.php [hunk 37]
```diff
@@ -297,7 +248,15 @@ public function create()
 			$this->response->status(201);
 			return $item->toJSON($this->visitor());
 		} else {
+			$errors = array_map(function($error){
```
Comment (juliogreff) [inline sitebuilder/app/controllers/api/ItemsController.php]: Missing a space before the last brace

File: sitebuilder/app/controllers/items_controller.php [hunk 38]
```diff
@@ -2,6 +2,7 @@
 
 use app\models\Items;
 use meumobi\sitebuilder\validators\ItemsPersistenceValidator;
+use meumobi\sitebuilder\services\ItemCreation;
```
Comment (juliogreff) [inline sitebuilder/app/controllers/items_controller.php]: Alphabetical order

File: sitebuilder/lib/meumobi/sitebuilder/services/ItemCreation.php [hunk 39]
```diff
@@ -0,0 +1,114 @@
+<?php
+namespace meumobi\sitebuilder\services;
+
+use Model;
+use Inflector;
+use meumobi\sitebuilder\validators\ItemsPersistenceValidator;
+use meumobi\sitebuilder\Logger;
+use meumobi\sitebuilder\WorkerManager;
```
Comment (juliogreff) [inline sitebuilder/lib/meumobi/sitebuilder/services/ItemCreation.php]: Alphabetical order here as well too

File: sitebuilder/lib/meumobi/sitebuilder/workers/UpdateFeedsWorker.php [hunk 40]
```diff
@@ -18,6 +18,8 @@
 use lithium\data\Connections;
 use app\models\Items;
 use meumobi\sitebuilder\repositories\RecordNotFoundException;//TODO move exceptions for a more generic namespace
+use meumobi\sitebuilder\services\ItemCreation;
+use meumobi\sitebuilder\Logger;
 use app\models\extensions\Rss;
 use app\models\items\Articles;
 use Video;
```
Comment (juliogreff) [inline sitebuilder/lib/meumobi/sitebuilder/workers/UpdateFeedsWorker.php]: Alphabetical order

File: sitebuilder/lib/meumobi/sitebuilder/services/ItemCreation.php (hunk 39 above)
Comment (juliogreff) [inline sitebuilder/lib/meumobi/sitebuilder/services/ItemCreation.php]: Alphabetical order is still missing here

**Comment by juliogreff** [comment]
The commits are not atomic.

- 45429f2 is more or less fine, but a lot of changes that it should introduce are actually introduced in the later commits. For example, there's a dangling .feature file that should've never been included in the first place.
- 08f8c8a introduces the service from the previous commits besides only extracting the ordering from that class. There's probably more than that, but I didn't look further
- bd9e3ac does validation changes **and** code cleanup. The **and** pretty much sums it up: this commit does more than one unrelated thing. I also didn't need to look further

One good strategy for grouping changes in cases like this is thinking about how you'd revert pieces of all the functionality you added. Here's how I'd do it:

- I'd first of all only introduce the new service. No other files would be touched.
- I'd then point all the functionality to that service. I wouldn't change anything else related do code cleanup, documentation, validation, etc. This includes deleting all the observers.
- After that, I'd commit the validation changes, and the translations for them. This includes the changes you made to the way errors are returned to the user
- After, remove the dangling ItemsController::add and corresponding documentation
- If there's anything left, it will probably just be cosmetic changes to the code. You can bundle all of them together if it makes sense.

Remember that ```git add -p``` is your friend. I'm hoping to be able to merge this today

**Comment by juliogreff** [comment]
Almost there. 4cf5f5c has a weird change that doesn't look like it should be there though. Fix it and let me know.
